"""empty message

Revision ID: 2c9a16b628fb
Revises: b97a72faa83
Create Date: 2014-08-09 01:12:17.742000

"""

# revision identifiers, used by Alembic.
revision = '2c9a16b628fb'
down_revision = 'b97a72faa83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
