"""empty message

Revision ID: 36e95644999d
Revises: 2c9a16b628fb
Create Date: 2014-08-09 01:15:05.084000

"""

# revision identifiers, used by Alembic.
revision = '36e95644999d'
down_revision = '2c9a16b628fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
