"""empty message

Revision ID: 4921e5493708
Revises: 2fce1beac0f6
Create Date: 2014-08-09 01:00:03.224000

"""

# revision identifiers, used by Alembic.
revision = '4921e5493708'
down_revision = '2fce1beac0f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'count')
    ### end Alembic commands ###
