"""empty message

Revision ID: b97a72faa83
Revises: 4921e5493708
Create Date: 2014-08-09 01:09:53.802000

"""

# revision identifiers, used by Alembic.
revision = 'b97a72faa83'
down_revision = '4921e5493708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
